#
# Travis CI configuration file
#

dist: trusty
sudo: required

addons:
  apt:
    packages:
    - libunwind8

install:
 - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
 - sudo apt-get update
 - sudo apt-get install dotnet-dev-1.0.1

script:
  - dotnet restore
  - cd src/NLibuv
  - dotnet build --framework "netstandard1.3"
  - cd ../..
  - cd test/NLibuv.Tests
  - dotnet restore && dotnet build && dotnet test
