#
# Travis CI configuration file
#

dist: trusty
language: csharp
sudo: required

addons:
  apt:
    packages:
    - libunwind8

mono:
  - 4.2.1

install:
 - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview2-003121 --install-dir ~/dotnet
 - sudo ln -s ~/dotnet/dotnet /usr/local/bin

solution: NLibuv.sln

script:
  - dotnet restore
  - cd src/NLibuv
  - dotnet build --framework "netstandard1.3"
  - cd ../..
  - cd test/NLibuv.Tests
  - dotnet restore && dotnet build && dotnet test
